### ISSUE TITLE
Push reject error

### ISSUE THREAD

**Issue by zweminthu** [Team-3-DevOps/Coursework#1]
Firstly, created new repository in GitHub including code of conduct and product backlog.
Then, clone that repository to the local machine and continue the assigned task and facing with push reject error.

**Comment by WaiLinn-Oo** [comment]
This happens as you first created new repo on github which would need java sources. 
Find a way of adding java and maven source to your current project. Sometimes, it happens when you push changes without requesting pull. If my suggestion doesn't seen work, delete current repo and first create in local, then commit to github. Best of Luck!

**Comment by zweminthu** [comment]
It works Thz for ur suggestion! :)

**Comment by WaiLinn-Oo** [comment]
you're welcome dude :3
